"""
Carton Installer
================
Drag and drop this file onto Maya's viewport.
The Carton package manager will be installed automatically.
"""

import base64
import io
import json
import os
import shutil
import sys
import zipfile

# ---- Settings (auto-embedded by CI/CD) ----
CARTON_VERSION = "__VERSION__"
CARTON_LANGUAGE = "__LANGUAGE__"
SUPPORTED_MAYA = ["2024", "2025", "2026", "2027"]

# CI/CD pipeline embeds the Base64-encoded zip here
CARTON_ZIP_B64 = """__CARTON_ZIP_B64__"""

# ---- Bootstrap ----
USERSETUP_HOOK = """\

# --- Carton Bootstrap ---
try:
    import carton_bootstrap
    carton_bootstrap.start()
except Exception as e:
    import traceback
    print("[Carton] Bootstrap failed: {}".format(e))
    traceback.print_exc()
# --- End Carton Bootstrap ---
"""

BOOTSTRAP_PY = '''\
"""Carton bootstrap — auto-generated by installer."""

import json
import os
import shutil
import sys
import traceback
import zipfile


def _find_default_install_dir():
    if sys.platform == "win32":
        return os.path.normpath(os.path.expanduser("~/Documents/maya/carton"))
    return os.path.normpath(os.path.expanduser("~/maya/carton"))


def _get_install_dir():
    default = _find_default_install_dir()
    config_path = os.path.join(default, "config.json")
    if os.path.exists(config_path):
        try:
            with open(config_path, "r", encoding="utf-8") as f:
                config = json.load(f)
            return config.get("install_dir", default)
        except (json.JSONDecodeError, OSError):
            pass
    return default


def _apply_pending_update(install_dir):
    pending_file = os.path.join(install_dir, "pending_update.json")
    if not os.path.exists(pending_file):
        return
    with open(pending_file, "r", encoding="utf-8") as f:
        pending = json.load(f)
    carton_dir = os.path.join(install_dir, "carton")
    backup_dir = os.path.join(install_dir, "carton.bak")
    staged_zip = os.path.join(install_dir, pending["staged_zip"])
    if not os.path.exists(staged_zip):
        print("[Carton] Staged zip not found: {}".format(staged_zip))
        os.remove(pending_file)
        return
    try:
        if os.path.exists(backup_dir):
            shutil.rmtree(backup_dir)
        if os.path.exists(carton_dir):
            os.rename(carton_dir, backup_dir)
        with zipfile.ZipFile(staged_zip, "r") as zf:
            zf.extractall(install_dir)
        os.remove(pending_file)
        if os.path.exists(backup_dir):
            shutil.rmtree(backup_dir)
        if os.path.exists(staged_zip):
            os.remove(staged_zip)
        staging_dir = os.path.dirname(staged_zip)
        if os.path.isdir(staging_dir) and not os.listdir(staging_dir):
            os.rmdir(staging_dir)
        print("[Carton] Updated to v{}".format(pending["version"]))
    except Exception:
        traceback.print_exc()
        if os.path.exists(backup_dir):
            if os.path.exists(carton_dir):
                shutil.rmtree(carton_dir)
            os.rename(backup_dir, carton_dir)
        if os.path.exists(pending_file):
            os.remove(pending_file)
        print("[Carton] Update failed, rolled back")


def start():
    install_dir = _get_install_dir()
    _apply_pending_update(install_dir)
    if install_dir not in sys.path:
        sys.path.insert(0, install_dir)
    import carton
    carton.startup()
'''

# ---- Initial config.json ----
DEFAULT_CONFIG = {
    "registries": [],
    "install_dir": "",
    "auto_check_updates": True,
    "github_repo": "cignoir/carton",
}


def _show_dialog(title, message, buttons=None):
    import maya.cmds as cmds
    buttons = buttons or ["OK"]
    return cmds.confirmDialog(
        title=title, message=message, button=buttons,
        defaultButton=buttons[0], cancelButton=buttons[-1],
    )


def _detect_install_dir():
    """Detect install directory — same logic as carton.core.config."""
    if sys.platform == "win32":
        return os.path.normpath(os.path.expanduser("~/Documents/maya/carton"))
    return os.path.normpath(os.path.expanduser("~/maya/carton"))


def onMayaDroppedPythonFile(*args, **kwargs):
    """Maya Drag & Drop entry point."""
    import maya.cmds as cmds

    maya_version = cmds.about(version=True)

    if maya_version not in SUPPORTED_MAYA:
        _show_dialog(
            "Carton",
            "Maya {} は非対応です。\n対応バージョン: {}".format(
                maya_version, ", ".join(SUPPORTED_MAYA)
            ),
        )
        return

    # Installation destination (shared across Maya versions)
    install_dir = _detect_install_dir()
    carton_pkg_dir = os.path.join(install_dir, "carton")

    # Check for existing installation
    if os.path.exists(carton_pkg_dir):
        current = "unknown"
        try:
            init_path = os.path.join(carton_pkg_dir, "__init__.py")
            if os.path.exists(init_path):
                with open(init_path, "r", encoding="utf-8") as f:
                    for line in f:
                        if line.startswith("__version__"):
                            current = line.split("=")[1].strip().strip('"').strip("'")
                            break
        except OSError:
            pass

        result = _show_dialog(
            "Carton",
            "Carton {} が既にインストールされています。\n"
            "v{} で上書きしますか？".format(current, CARTON_VERSION),
            buttons=["上書き", "キャンセル"],
        )
        if result == "キャンセル":
            return
        shutil.rmtree(carton_pkg_dir)

    # Extract zip
    try:
        zip_data = base64.b64decode(CARTON_ZIP_B64)
    except Exception as e:
        _show_dialog("Carton", "インストーラデータが破損しています。\n{}".format(e))
        return

    os.makedirs(install_dir, exist_ok=True)
    with zipfile.ZipFile(io.BytesIO(zip_data), "r") as zf:
        zf.extractall(install_dir)

    # Deploy bootstrap
    scripts_dir = cmds.internalVar(userScriptDir=True)
    os.makedirs(scripts_dir, exist_ok=True)

    bootstrap_path = os.path.join(scripts_dir, "carton_bootstrap.py")
    with open(bootstrap_path, "w", encoding="utf-8") as f:
        f.write(BOOTSTRAP_PY)

    usersetup_path = os.path.join(scripts_dir, "userSetup.py")
    if os.path.exists(usersetup_path):
        with open(usersetup_path, "r", encoding="utf-8") as f:
            existing = f.read()
        if "carton_bootstrap" not in existing:
            with open(usersetup_path, "a", encoding="utf-8") as f:
                f.write(USERSETUP_HOOK)
    else:
        with open(usersetup_path, "w", encoding="utf-8") as f:
            f.write(USERSETUP_HOOK)

    # Generate or update config.json
    config_path = os.path.join(install_dir, "config.json")
    if os.path.exists(config_path):
        with open(config_path, "r", encoding="utf-8") as f:
            config = json.load(f)
    else:
        config = DEFAULT_CONFIG.copy()
        config["install_dir"] = install_dir
    config["language"] = CARTON_LANGUAGE
    with open(config_path, "w", encoding="utf-8") as f:
        json.dump(config, f, indent=2, ensure_ascii=False)

    _show_dialog(
        "Carton",
        "Carton v{} をインストールしました。\n"
        "Maya を再起動してください。".format(CARTON_VERSION),
    )
    print("[Carton] Installed v{} to {}".format(CARTON_VERSION, install_dir))
